#!/usr/bin/env bash
# Build the windeploykit-dialog native macOS prompt helper (tools/windeploykit-dialog/main.swift)
# as a universal (x86_64 + arm64) binary and commit it under vendor/binaries/.
# Requires Xcode command line tools (swiftc). Rerun only when main.swift changes.
#
# Output:
#   vendor/binaries/dialog-macos/windeploykit-dialog-universal        (committed)
#   vendor/binaries/dialog-macos/windeploykit-dialog-{arch}-apple-darwin

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
src="${repo_root}/tools/windeploykit-dialog/main.swift"
icon_png="${repo_root}/app/src-tauri/icons/256x256.png"
out_dir="${repo_root}/vendor/binaries/dialog-macos"
build_dir="$(mktemp -d)"
trap 'rm -rf "${build_dir}"' EXIT

mkdir -p "${out_dir}"

# Embed the app icon (base64) so the binary is fully self-contained — no
# runtime path resolution, works in dev checkouts and the packaged .app alike.
icon_swift="${build_dir}/icon-data.swift"
{
  echo "// Generated by build-windeploykit-dialog.sh from app/src-tauri/icons/256x256.png — do not edit."
  printf 'let embeddedIconBase64 = "'
  base64 -i "${icon_png}" | tr -d '\n'
  echo '"'
} > "${icon_swift}"

echo "==> Building windeploykit-dialog (x86_64)"
swiftc -O -target x86_64-apple-macos12 -o "${build_dir}/windeploykit-dialog-x86_64" "${src}" "${icon_swift}"

echo "==> Building windeploykit-dialog (arm64)"
swiftc -O -target arm64-apple-macos12 -o "${build_dir}/windeploykit-dialog-arm64" "${src}" "${icon_swift}"

echo "==> Creating universal binary"
lipo -create \
  "${build_dir}/windeploykit-dialog-x86_64" \
  "${build_dir}/windeploykit-dialog-arm64" \
  -output "${out_dir}/windeploykit-dialog-universal"

cp -f "${build_dir}/windeploykit-dialog-x86_64" "${out_dir}/windeploykit-dialog-x86_64-apple-darwin"
cp -f "${build_dir}/windeploykit-dialog-arm64" "${out_dir}/windeploykit-dialog-aarch64-apple-darwin"
chmod +x "${out_dir}"/windeploykit-dialog-*

# Ad-hoc sign so a stripped quarantine attr doesn't leave an unsigned binary.
for bin in "${out_dir}"/windeploykit-dialog-*; do
  codesign --force --sign - "${bin}" >/dev/null 2>&1 || true
done

lipo -info "${out_dir}/windeploykit-dialog-universal"
echo "==> Done. git add vendor/binaries/dialog-macos/"
